### ISSUE TITLE
Default user-agent is likely going to be blocked in most cases

### ISSUE THREAD

**Issue by benjojo** [PuerkitoBio/gocrawl#41]
First of all, Why (by defaults) have two user agents?

You are using

`Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2` for page crawling and then  `Googlebot (gocrawl v0.4)` for when you are grabbing robots.txt from what I can see.

Impersonating googlebot is already playing with fire against systems that detect and block things that claim to be Google Bot.

But also why have two different? Does this actually gain anything, Why not ship a user agent that explains that your program is a crawler, it's better to be honest than a WAF detecting that your request isnt what it says it is.

I understand these are defaults, but encouraging people to use these User-Agent strings by default IMO is a bad idea.

**Comment by PuerkitoBio** [comment]
Hi Ben,

I may misinterpret your intentions, but the tone of your comment comes out as surprisingly aggressive, I read it as implying that this package is dishonest and borders on shady stuff. I find this surprising because the whole point of it is to actually play nice with robots.txt policies, something that is oh so easy to ignore.

As you allude to, those user-agents are only defaults, and this is what the README says:

*    **UserAgent** : The user-agent string used to fetch the pages. Defaults to the Firefox 15 on Windows user-agent string.

*    **RobotUserAgent** : The robot's user-agent string used to fetch and query robots.txt for permission to crawl an URL. Defaults to `Googlebot (gocrawl vM.m)` where `M.m` is the major and minor version of gocrawl. See the [robots exclusion protocol][robprot] ([full specification as interpreted by Google here][robspec]) for details about the rule-matching based on the robot's user agent. **It is good practice to include contact information in the user agent should the site owner need to contact you.**

The reason I did put Googlebot back then (I think - that was a long time ago) was because a huge number of sites have incomplete robots.txt files, with a policy only for Googlebot. If anything, that's to be *more* honest and avoid falling in the cracks because a no-name bot has no policy and ends up crawling anything. It does mention what it actually is (gocrawl) in the user-agent.

The reason for the other user-agent string is because many sites (sadly) still rely on that  to render content, so using a well-known browser user-agent sounded like a good idea back then.

And again, those are defaults, if someone does build something serious with this, I sure hope they set it to something meaningful.

You'll notice that I mention "back then" a lot because I don't really maintain that repo anymore, I created fetchbot since then, and it doesn't have that whole double user-agent stuff with googlebot defaults, just one with fetchbot and the repo.

Hope that clarifies it. I agree those are not the best defaults - I haven't used those defaults in fetchbot - but changing it now could break working apps, and I certainly disagree with the implied idea that those defaults make it a dishonest package - heck, user agents have been used since forever to claim to be something they are not, for the  same purpose of not falling in the cracks.

Martin

**Comment by benjojo** [comment]
Not meaning to be aggressive :)

I do not know of any system that serves you different kinds of robots.txt files based on the user agent you send, So you may want to just unify `RobotUserAgent` with `UserAgent` since all of the information should be given with a robots.txt, not selective to the user agent that requested it.

Sure, UserAgents can be set to what ever people want, but it is nice to have a user agent that by default says what you are when crawling pages, even if it's a splice one of a browser, like for example:

`Mozilla/5.0 (Windows NT 6.1; rv:15.0; ) gocrawl/0.4 Gecko/20120716 Firefox/15.0a2`

Just looking for more understandability when people read their logs I guess.

**Comment by PuerkitoBio** [comment]
> I do not know of any system that serves you different kinds of robots.txt files based on the user agent you send

Neither do I, what I said is that many systems have a robots.txt only for googlebot, no entry for other bots and no catch-all.

Adding the gocrawl tag in the browser user-agent is certainly harmless, so yeah I'll add that. For the bot user-agent, that's likely to break existing code, so I'll leave it like that.

**Comment by DamonHD** [comment]
I came across this page while trying to work out what was the apparent bad bot that was impersonating Googlebot in my logs just now.  My instinct is to block anything claiming to be something that it clearly isn't, and therefore may well be malicious, and I'm sure I'm not alone.
