### ISSUE TITLE
Limit of active workers

### ISSUE THREAD

**Issue by co11ter** [PuerkitoBio/gocrawl#49]
Hi!
How I can limit it?

**Comment by PuerkitoBio** [comment]
Hi Alexander,

There is a new goroutine per host, so if you absolutely must limit it, I believe you could do this in the filter method (haven't used gocrawl myself in a while), but you have to keep track of active hosts and compare with the incoming URL, there's no built-in support for that. However, note that goroutines are really cheap, e.g. the http server in the stdlib spawns a new goroutine for each request.

What you may want, instead of limiting the number of workers (goroutines), is limit the number of active requests, to limit file descriptors? That can be done with a semaphore pattern using a channel, and acquire/release in the appropriate extender methods. It's probably easier to implement in fetchbot (https://github.com/PuerkitoBio/fetchbot) than in gocrawl though (I've never done it in gocrawl, it is trivial in fetchbot).

Hope this helps,
Martin

**Comment by co11ter** [comment]
Thank you. I'll try filter method.
