### ISSUE TITLE
Treat example.com/robots.txt and www.example.com/robots.txt differently

### ISSUE THREAD

**Issue by ranvis** [PuerkitoBio/gocrawl#53]
Different hosts have different robots.txt.
It is inconsistent to use normalized URL (strip www.) to build /robots.txt URL while subsequent crawling URLs are not normalized (with www.).

**Comment by PuerkitoBio** [comment]
This is controlled by the `Options.URLNormalizationFlags` option. It defaults to `purell.FlagsAllGreedy` which is more aggressive (another unfortunate default, but still just a default). You can set it to `purell.FlagsSafe` or control exactly what you want to apply using purell's flags.

I understand your point about inconsistency, the default Fetch extender method uses the non-normalized URL of the page, while the robots.txt URL is constructed from the normalized URL of the page (e.g. given "http://www.example.com/page" normalized to "http://example.com/page", the robots.txt is "http://example.com/robots.txt"). There's a comment in the code pointing out this caveat, but that's the role of the normalization strategy - if that causes a problem, you should use a less aggressive normalization or provide a custom Fetch implementation. I believe this is very unlikely to be an issue in practice.

**Comment by ranvis** [comment]
Hmm my understand is that with default options, given URL http://www.example.com/page, gocrawl accesses normalized http://example.com/robots.txt, and then queued http://www.example.com/page
while URL duplication check is done against normalized http://example.com/page
So I was wondering what is the point of using normalized URL of robots.txt when accessing not testing.
Is that wrong, i.e. gocrawl actually accesses http://example.com/page ?

**Comment by PuerkitoBio** [comment]
Yes, that is correct, by default (you can of course provide your own Fetch implementation that uses the normalized URL - gocrawl doesn't "queue" the non-normalized URL, it queues an URLContext, which contains both versions and other state data). As I mentioned, it can be solved in various ways, either by changing the normalization flags to something safer, or by providing a custom Fetch in your Extender, so that it uses the normalized form everywhere.

**Comment by ranvis** [comment]
Then is it possible to build robots.txt URL based on non-normalized URL?
Default options are kept the same and it must not affect to the behavior for user's perspective.
And if the user unknowingly using normalize-www. option, he get less chance of getting the wrong robots.txt.

**Comment by PuerkitoBio** [comment]
Good question, I'll take a look. I don't think that's a major issue though (in fact I think it's mostly a theoretical one, I would be very surprised if a website had different rules for www. vs no-www).

**Comment by PuerkitoBio** [comment]
Well, it's not really doable, because the normalization determines the relationship between workers and host (a new worker is started for each normalized host). You don't want 2 hosts on example.com and www.example.com because it's very likely hitting the same server. In fact, the normalized URL is used to store the visited URLs, start a worker per (normalized) host, and request the robots.txt (using the normalized form). So not using the normalized form for the robots.txt would actually make this incoherent (the worker for "example.com" would request the robots for "www.example.com").

The way to solve this, in the rare cases where it matters (IMHO), is via the normalization flag and/or the Fetch implementation.

**Comment by ranvis** [comment]
Hmm, OK. I think I understand how it works now.
Really thank you for taking time to investigate.
Also it was good that I had known about how the defaults were set historically.

**Comment by PuerkitoBio** [comment]
No problem, thanks for reporting the issues, it did make the package better. Have fun with it!

Martin
