### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Arnold1** [PuerkitoBio/gocrawl#61]
Hi, 
how can i use a SOCKS5 proxy with your library? e.g:

```
 // Create a socks5 dialer
  dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:9050", nil, proxy.Direct)
  if err != nil {
    log.Fatal(err)
  }

  // Setup HTTP transport
  tr := &http.Transport{
    Dial: dialer.Dial,
  }
  client := &http.Client{Transport: tr}

  res, err := client.Get("http://google.com")
```

how can you send a post request to login to a website?

Thanks,
Arnold

**Comment by PuerkitoBio** [comment]
To use your SOCKS5-based HTTP client, you can simply set `gocrawl.HttpClient = client` before starting the crawl process. Another option is to provide a custom `Fetch` implementation, so that it uses that SOCKS5-based HTTP client.

Note however that gocrawl only crawls with GET (and HEAD) requests. If you want a more flexible though less frameworky crawling package, I suggest my [fetchbot](https://github.com/PuerkitoBio/fetchbot) package. You can still use your SOCKS5 client when creating the Fetcher value, i.e. `f := &fetchbot.Fetcher{HttpClient: client}`, and you can enqueue POST URLs and provide HTTP headers and/or a request body by calling `Queue.Send(cmd)` where `cmd` is a custom implementation of the `fetchbot.Command` interface that implements `fetchbot.HeaderProvider` and/or `fetchbot.ReaderProvider`. See the package docs for details.

Hope that helps,
Martin
